run_config:
  resume: False
  train: True
  eval: True
  save: True
  save_path: "./checkpoints/accfiy"
  eval_path: "./checkpoints/accfiy/eval"

trainer_config:
  num_epochs: 2
  learning_rate: 0.0003
  beta1: 0.9
  beta2: 0.95
  weight_decay: 0.1
  total_steps: 100
  warmup_ratio: 0.1
  gradient_accumulation_steps: 1
  logging_steps: 10
  accelerate: True
  mixed_precision: True
  checkpoint_path: "./checkpoint.pt"
  decoder_only_training: False

model_config:
  model_name: "accfiy"
  tokenizer_name: "deepseek-ai/DeepSeek-Coder-1.3B-base"
  dim: 768
  num_layers: 12
  num_heads: 8
  ff_hidden_dim: 2048

dataloader_config:
  dataset_name: "allenai/c4"
  batch_size: 16
  max_length: 256
  size: 1000
  num_workers: 4
